### ISSUE TITLE
May have just removed a wiki page

### ISSUE THREAD

**Issue by fzgregor** [wavesoft/jbb#4]
Hi,

I'm sorry i may have just removed one of your wiki pages.

I followed https://t.co/S2pzYHlCgL on your twitter post https://twitter.com/wavesoftgr/status/740101553726443520 and expected to see some comparision between messagepack and your encoding.

However, an empty "Create new page" form appeared where I just put "hello world".
To my surprise the page got created...

Sorry

**Comment by wavesoft** [comment]
Hello @rotschopf . Don't worry, it's not so easy to delete a wiki page. The missing link was my fault. I was re-arranging the pages and I might have renamed it.

For your case, my guess is that github forked the wiki pages in your account and saved your changes there?
